feat(oauth): oauth.js
sid22/smart-on-fhir-demo pull request #22
Opened 2020-05-07 11:54 UTC by RhnSaxena

Fixes #8

2020-05-07 12:05 UTC, sid22 commented on lib/oauth.js
> +  application_token = obj;
Why not just return the obj?

2020-05-07 13:54 UTC, RhnSaxena commented
@sid22 please review the changes.

2020-05-07 14:18 UTC, sid22 requested changes
Looks good otherwise, have you tested it locally ?

2020-05-07 14:18 UTC, sid22 commented on lib/oauth.js
> +      return obj;
```
return {
  "status" : "Failure",
  "code" : error.status,
  "message" : error,
}
```

2020-05-07 14:37 UTC, RhnSaxena commented on lib/oauth.js
> +      return obj;
Yes, I have tested it. It's working.

2020-05-08 09:48 UTC, RhnSaxena commented on lib/oauth.js
> +  application_token = obj;
Did it.

2020-05-08 10:23 UTC, merged